"""Added categories to inquiry

Revision ID: 177eaca8ffff
Revises: ed29d0dae793
Create Date: 2026-04-23 07:10:08.838590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177eaca8ffff'
down_revision = 'ed29d0dae793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_categories', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_inquiries', schema=None) as batch_op:
        batch_op.drop_column('equipment_categories')

    # ### end Alembic commands ###
