"""Added phone to inquiry

Revision ID: 671aa4234840
Revises: 177eaca8ffff
Create Date: 2026-04-23 09:04:26.025244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671aa4234840'
down_revision = '177eaca8ffff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_inquiries', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
